name: dotnet CI

on:
  push:
    branches:
      - main
      - dev
env:
  IMAGE: gcr.io/${{ secrets.PROJECT_ID }}/api

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Setup docker
        run: gcloud --quiet auth configure-docker

      - name: Build image
        run: docker build --build-arg VITE_API_KEY=${{ secrets.AGRC_API_KEY }} --file ./src/api/Api.Dockerfile --tag gcr.io/${{ secrets.PROJECT_ID }}/api .

      # Push the Docker image to Google Container Registry
      - name: Publish image
        run: docker push "gcr.io/${{ secrets.PROJECT_ID }}/api"

      - name: Create cloud run revision
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --platform "managed" \
            --region "us-central1" \
            --image "$IMAGE:latest"
