name: dotnet CI

on:
  push:
    branches:
      - main
      - dev
env:
  IMAGE: gcr.io/${{ secrets.PROJECT_ID }}/api
  SERVICE_NAME: uic-inventory-api

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: dev

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: ⬇️ Set up code
        uses: actions/checkout@v2

      - id: auth
        name: 🗝️ Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.3.1
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: 🐳 Setup docker
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: ☁️ Setup gcloud
        run: |
          gcloud auth login --brief --cred-file=${{ steps.auth.outputs.credentials_file_path }}
          gcloud --quiet config set project ${{ secrets.PROJECT_ID }}

      - name: 📦 Build image
        run: docker build --build-arg VITE_API_KEY=${{ secrets.AGRC_API_KEY }} --file ./src/api/Api.Dockerfile --tag gcr.io/${{ secrets.PROJECT_ID }}/api .

      - name: 📤 Publish image
        run: docker push "gcr.io/${{ secrets.PROJECT_ID }}/api"

      - name: 🚀 Create cloud run revision
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --platform "managed" \
            --region "us-central1" \
            --image "$IMAGE:latest"
