name: Scheduled Events

on:
  schedule:
    - cron: "0 6 1 * *"
  workflow_dispatch:

jobs:
  update:
    name: Update and publish malware scanner
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: dev

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v3
        with:
          repository: GoogleCloudPlatform/docker-clamav-malware-scanner

      - id: auth
        name: 🗝️ Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          token_format: access_token
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: 🐳 Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@v1

      - name: 🗝️ Authenticate Docker to Google CLoud
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: 📦 Build and push image
        uses: docker/build-push-action@v2
        with:
          file: ./cloudrun-malware-scanner/Dockerfile
          builder: ${{ steps.builder.outputs.name }}
          tags: gcr.io/${{ secrets.PROJECT_ID }}/malware-scanner
          context: ./cloudrun-malware-scanner
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 🚀 Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: malware-scanner
          image: gcr.io/${{ secrets.PROJECT_ID }}/malware-scanner
          region: us-central1
          flags: |
            --service-account=malware-scanner-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
            --no-cpu-throttling
            --cpu=1
            --memory=4Gi
          env_vars: >
            UNSCANNED_BUCKET=${{ secrets.PROJECT_ID }}-unscanned,
            QUARANTINED_BUCKET=${{ secrets.PROJECT_ID }}-quarantined,
            CLEAN_BUCKET=${{ secrets.PROJECT_ID }}-documents
