name: Workflow Dispatch Events

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish malware scanner
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: dev

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v4
        with:
          show-progress: false
          repository: GoogleCloudPlatform/docker-clamav-malware-scanner

      - name: 🛠️ Create config.json
        uses: devops-actions/json-to-file@v1.0.3
        with:
          json: |
            {
              "comments": [],
              "buckets": [{
                "unscanned": "${{ secrets.PROJECT_ID }}-unscanned",
                "clean": "${{ secrets.PROJECT_ID }}-documents",
                "quarantined": "${{ secrets.PROJECT_ID }}-quarantined"
              }],
              "ClamCvdMirrorBucket": "${{ secrets.PROJECT_ID }}-cvd-mirror"
            }
          filename: ./cloudrun-malware-scanner/config.json

      - id: auth
        name: 🗝️ Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          token_format: access_token
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: 🐳 Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@v3

      - name: 🏷️ Extract tags from GitHub
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/images/malware-scanner
          tags: |
            type=ref,suffix=-{{sha}},event=branch
            type=ref,prefix=pr-,suffix=-{{sha}},event=pr
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: 🗝️ Authenticate Docker to Google Cloud
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: 📦 Build and push image
        uses: docker/build-push-action@v5
        with:
          file: ./cloudrun-malware-scanner/Dockerfile
          provenance: false
          builder: ${{ steps.builder.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          context: ./cloudrun-malware-scanner
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 🔍️ Set image name
        run: |
          IMAGE_ID=$(echo $DOCKER_METADATA_OUTPUT_TAGS | cut -d ' ' -f 1)
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

      - name: 🚀 Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: malware-scanner
          image: ${{ env.IMAGE_ID }}
          region: us-central1
          flags: |
            --service-account=malware-scanner-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
            --no-allow-unauthenticated
            --memory 4Gi
            --cpu 1
            --concurrency 20
            --min-instances 0
            --max-instances 5
            --no-cpu-throttling
            --cpu-boost
